<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChartLibRepository extends EntityRepository
{
    public function getWithType($params)
    {
        $query = $this->createQueryBuilder('cl')
            ->join('cl.type', 't')
            ->addSelect('t');

        if (array_key_exists('idRecord', $params)) {
            $query->where('cl.idRecord = :idRecord')
                ->setParameter('idRecord', $params['idRecord']);
        }

        if (array_key_exists('idGroupe', $params)) {
        }

        return $query->getQuery()
            ->getResult();
    }

}
