<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use VideoGamesRecords\CoreBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * @param array $params
     * @return \VideoGamesRecords\CoreBundle\Entity\Game[]
     */
    public function queryAlpha($params = [])
    {
        $query = $this->createQueryBuilder('g');

        if (array_key_exists('idSerie', $params) && $params['idSerie'] !== null) {
            $query
                ->where('g.idSerie = :idSerie')
                ->setParameter('idSerie', $params['idSerie']);
        }

        if (array_key_exists('letter', $params) && $params['letter'] !== null) {
            $letter = $params['letter'];
            if ($letter == '0') {
                $query
                    ->innerJoin('g.translations', 'translation')
                    ->where('SUBSTRING(translation.name , 1, 1) NOT IN (:list)')
                    ->setParameter('list', range('a', 'z'));
            } else {
                $query
                    ->innerJoin('g.translations', 'translation')
                    ->where('SUBSTRING(translation.name , 1, 1) = :letter')
                    ->setParameter('letter', $letter);
            }
            $query->orderBy('translation.name');
        }


        $query
            ->andWhere('g.status = :status')
            ->setParameter('status', Game::STATUS_ACTIVE);

        //----- Add platforms
        $query->join('g.platforms', 'p')
            ->addSelect('p');


        return $query->getQuery()->getResult();
    }
}
