<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{

    public function queryAlpha($params = array())
    {
        $query = $this->createQueryBuilder('g');

        if (array_key_exists('idSerie', $params) && $params['idSerie'] !== null) {
            $query->where('g.idSerie = :idSerie')
                ->setParameter('idSerie', $params['idSerie']);
        }

        return $query->getQuery();
    }
}
