<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{

    public function getWidthGame($id)
    {
        $query = $this->createQueryBuilder('gr')
            ->join('gr.game', 'ga')
            ->addSelect('ga')
            ->where('gr.idGroupe = :idGroupe')
            ->setParameter('idGroupe', $id);

        return $query->getQuery()
            ->getOneOrNullResult();
    }
}
