<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use VideoGamesRecords\CoreBundle\Tools\Score;

/**
 * PlayerChartLibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerChartLibRepository extends EntityRepository
{
    /**
     * @param array $params idPlayer|idChart|idGroupe
     * @return array
     */
    public function getFormValues($params = [])
    {
        $query = $this->createQueryBuilder('pcl')
            ->join('pcl.libChart', 'lib')
            ->addSelect('lib')
            ->join('lib.type', 'type')
            ->addSelect('type')
            ->orderBy('lib.chart')
            ->addOrderBy('pcl.libChart');

        $query->where('pcl.player = :idPlayer')
            ->setParameter('idPlayer', $params['idPlayer']);

        if (array_key_exists('idChart', $params)) {
            $query->andWhere('lib.chart = :idChart')
                ->setParameter('idChart', $params['idChart']);
        }

        $result = $query->getQuery()->getResult();
        $data = [];

        foreach ($result as $row) {
            /** @var \VideoGamesRecords\CoreBundle\Entity\PlayerChartLib $row */
            $data['player_' . $row->getLibChart()->getChart()->getIdChart() . '_' . $row->getLibChart()->getIdLibChart()] = $row->getValue();
            $values = Score::getValues($row->getLibChart()->getType()->getMask(), $row->getValue());
            $i = 1;
            foreach ($values as $key => $value) {
                $data['value_' . $row->getLibChart()->getChart()->getIdChart() . '_' . $row->getLibChart()->getIdLibChart() . '_' . $i++] = $value['value'];
            }
        }

        return $data;
    }
}
