<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use VideoGamesRecords\CoreBundle\Tools\Score;

/**
 * PlayerChartLibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerChartLibRepository extends EntityRepository
{
    /**
     * @param array $params idPlayer|idChart|idGroupe
     * @return array
     */
    public function getFormValues($params = array())
    {
        $query = $this->createQueryBuilder('ucl')
            ->join('ucl.lib', 'lib')
            ->addSelect('lib')
            ->join('lib.type', 'type')
            ->addSelect('type')
            ->orderBy('lib.idChart')
            ->addOrderBy('ucl.idLibChart');

        $query->where('ucl.idPlayer = :idPlayer')
            ->setParameter('idPlayer', $params['idPlayer']);

        if (array_key_exists('idChart', $params)) {
            $query->andWhere('lib.idChart = :idChart')
                ->setParameter('idChart', $params['idChart']);
        }

        $result = $query->getQuery()->getResult();
        $data = array();

        foreach ($result as $row) {
            /** @var \VideoGamesRecords\CoreBundle\Entity\PlayerChartLib|\VideoGamesRecords\CoreBundle\Entity\ChartLib $row */
            $data['player_' . $row->getLib()->getIdChart() . '_' . $row->getIdLibChart()] = $row->getValue();
            $values = Score::getValues($row->getLib()->getType()->getMask(), $row->getValue());
            $i = 1;
            foreach ($values as $key => $value) {
                $data['value_' . $row->getLib()->getIdChart() . '_' . $row->getIdLibChart() . '_' . $i++] = $value['value'];
            }
        }

        return $data;
    }
}
