<?php

namespace VideoGamesRecords\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

/**
 * UserGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGameRepository extends EntityRepository
{
    /**
     * @param array $params idJeu|idLogin|limit|maxRank
     * @return array
     */
    public function getRankingPoints($params = array())
    {
        $query = $this->createQueryBuilder('ug')
            ->join('ug.user', 'u')
            ->addSelect('u') //----- for using ->getUser() on each result
            ->orderBy('ug.rank');

        $query->where('ug.idJeu = :idJeu')
           ->setParameter('idJeu', $params['idJeu']);

        if (array_key_exists('limit', $params)) {
            $query->setMaxResults($params['limit']);
        }

        if ( (array_key_exists('maxRank', $params)) && (array_key_exists('idLogin', $params)) ) {
            $query->andWhere('(ug.rank <= :maxRank OR ug.idMembre = :idLogin)')
                ->setParameter('maxRank', $params['maxRank'])
                ->setParameter('idLogin', $params['idLogin']);
        } else if (array_key_exists('maxRank', $params)) {
            $query->andWhere('ug.rank <= :maxRank')
                ->setParameter('maxRank', $params['maxRank']);
        }
        return $query->getQuery()->getResult();
    }


    /**
     * @param array $params idJeu|idLogin|limit|maxRank
     * @return array
     */
    public function getRankingMedals($params = array())
    {
        $query = $this->createQueryBuilder('ug')
            ->join('ug.user', 'u')
            ->addSelect('u') //----- for using ->getUser() on each result
            ->orderBy('ug.rankMedal');

        $query->where('ug.idJeu = :idJeu')
            ->setParameter('idJeu', $params['idJeu']);

        if (array_key_exists('limit', $params)) {
            $query->setMaxResults($params['limit']);
        }

        if ( (array_key_exists('maxRank', $params)) && (array_key_exists('idLogin', $params)) ) {
            $query->andWhere('(ug.rankMedal <= :maxRank OR ug.idMembre = :idLogin)')
                ->setParameter('maxRank', $params['maxRank'])
                ->setParameter('idLogin', $params['idLogin']);
        } else if (array_key_exists('maxRank', $params)) {
            $query->andWhere('ug.rankMedal <= :maxRank')
                ->setParameter('maxRank', $params['maxRank']);
        }
        return $query->getQuery()->getResult();
    }


    /**
     * @param $idJeu
     */
    public function maj($idJeu)
    {
        //----- delete
        $query = $this->_em->createQuery('DELETE VideoGamesRecords\CoreBundle\Entity\UserGame ug WHERE ug.idJeu = :idJeu');
        $query->setParameter('idJeu', $idJeu);
        $query->execute();

        //----- data without DLC
        $query = $this->_em->createQuery("
            SELECT
                 ug.idMembre,
                 SUM(ug.pointRecord) as pointRecordSansDLC,
                 SUM(ug.nbRecord) as nbRecordSansDLC,
                 SUM(ug.nbRecordProuve) as nbRecordProuveSansDLC
            FROM VideoGamesRecords\CoreBundle\Entity\UserGroup ug
            JOIN ug.group g
            WHERE g.idJeu = :idJeu
            AND g.boolDLC = 0
            GROUP BY ug.idMembre"
        );

        $dataWithoutDlc = array();

        $query->setParameter('idJeu', $idJeu);
        $result = $query->getResult();
        foreach ($result as $row) {
            $dataWithoutDlc[$row['idMembre']] = $row;
        }

        //----- select ans save result in array
        $query = $this->_em->createQuery("
            SELECT
                ug.idMembre,
                (g.idJeu) as idJeu,
                '' as rank,
                '' as rankMedal,
                SUM(ug.rank0) as rank0,
                SUM(ug.rank1) as rank1,
                SUM(ug.rank2) as rank2,
                SUM(ug.rank3) as rank3,
                SUM(ug.rank4) as rank4,
                SUM(ug.rank5) as rank5,
                SUM(ug.pointRecord) as pointRecord,
                SUM(ug.nbRecord) as nbRecord,
                SUM(ug.nbRecordProuve) as nbRecordProuve
            FROM VideoGamesRecords\CoreBundle\Entity\UserGroup ug
            JOIN ug.group g
            WHERE g.idJeu = :idJeu
            GROUP BY ug.idMembre
            ORDER BY pointRecord DESC"
        );


        $query->setParameter('idJeu', $idJeu);
        $result = $query->getResult();

        $list = array();
        foreach ($result as $row) {
            $row = array_merge($row, $dataWithoutDlc[$row['idMembre']]);
            $list[] = $row;
        }

        //----- add some data
        $list = \VideoGamesRecords\CoreBundle\Tools\Ranking::addRank($list, 'rank', array('pointRecord'), true);
        $list = \VideoGamesRecords\CoreBundle\Tools\Ranking::calculateGamePoints($list, array('rank', 'nbEqual'), 'pointJeu', 'pointRecord');
        $list = \VideoGamesRecords\CoreBundle\Tools\Ranking::order($list, array('rank0' => 'DESC', 'rank1' => 'DESC', 'rank2' => 'DESC', 'rank3' => 'DESC'));
        $list = \VideoGamesRecords\CoreBundle\Tools\Ranking::addRank($list, 'rankMedal', array('rank0', 'rank1', 'rank2', 'rank3', 'rank4', 'rank5'));

        $normalizer = new ObjectNormalizer();
        $serializer = new Serializer(array($normalizer));

        $game = $this->_em->find('VideoGamesRecords\CoreBundle\Entity\Game', $idJeu);

        foreach ($list as $row) {
            $userGame = $serializer->denormalize(
                $row,
                'VideoGamesRecords\CoreBundle\Entity\UserGame'
            );
            $userGame->setUser($this->_em->getReference('VideoGamesRecords\CoreBundle\Entity\User', $row['idMembre']));
            $userGame->setGame($game);

            $this->_em->persist($userGame);
            $this->_em->flush($userGame);
        }



    }
}
