services:
  sonata.admin.vgr.platform:
    class: VideoGamesRecords\CoreBundle\Admin\PlatformAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Platform
        manager_type: orm
        group: "group.games"
        label: "platform.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Platform/show.html.twig' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.serie:
    class: VideoGamesRecords\CoreBundle\Admin\SerieAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Serie
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\SerieAdminController
        manager_type: orm
        group: "group.games"
        label: "serie.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Serie/show.html.twig' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.game:
    class: VideoGamesRecords\CoreBundle\Admin\GameAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Game
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\GameAdminController
        manager_type: orm
        group: "group.games"
        label: "game.label"
        default: true
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Game/show.html.twig' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.group:
    class: VideoGamesRecords\CoreBundle\Admin\GroupAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Group
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\GroupAdminController
        manager_type: orm
        group: "group.games"
        label: "group.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.chart:
    class: VideoGamesRecords\CoreBundle\Admin\ChartAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Chart
        manager_type: orm
        group: "group.games"
        label: "chart.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.chart_type:
    class: VideoGamesRecords\CoreBundle\Admin\ChartTypeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\ChartType
        manager_type: orm
        group: "group.games"
        label: "chart_type.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.chart_lib:
    class: VideoGamesRecords\CoreBundle\Admin\ChartLibAdmin
    tags:
      - name: sonata.admin
        model_class: 'VideoGamesRecords\CoreBundle\Entity\ChartLib'
        manager_type: orm
        group: "group.games"
        label: "label.chart.lib"
        show_in_dashboard: false
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.proof_request:
    class: VideoGamesRecords\CoreBundle\Admin\ProofRequestAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\ProofRequest
        manager_type: orm
        group: "group.proofs"
        label: "proof_request.label"
    calls:
      - [ setTemplate, [ 'edit', '@@VideoGamesRecordsCore/Admin/Object/ProofRequest/edit.html.twig' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.proof:
    class: VideoGamesRecords\CoreBundle\Admin\ProofAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Proof
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\ProofAdminController
        manager_type: orm
        group: "group.proofs"
        label: "proof.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Proof/show.html.twig' ] ]
      - [ setTemplate, [ 'edit', '@@VideoGamesRecordsCore/Admin/Object/Proof/edit.html.twig' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.picture:
    class: VideoGamesRecords\CoreBundle\Admin\PictureAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Picture
        manager_type: orm
        group: "group.proofs"
        label: "picture.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Picture/show.html.twig' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.video:
    class: VideoGamesRecords\CoreBundle\Admin\VideoAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Video
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\VideoAdminController
        manager_type: orm
        group: "group.proofs"
        label: "video.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Video/show.html.twig' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.player:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Player
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\PlayerAdminController
        manager_type: orm
        group: "group.players"
        label: "player.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Player/show.html.twig' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.playerbadge:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerBadgeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerBadge
        manager_type: orm
        group: "group.badge"
        label: "player_badge.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.team:
    class: VideoGamesRecords\CoreBundle\Admin\TeamAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Team
        manager_type: orm
        group: "group.players"
        label: "team.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.team_request:
    class: VideoGamesRecords\CoreBundle\Admin\TeamRequestAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\TeamRequest
        manager_type: orm
        group: "group.players"
        label: "team_request.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.playerchart:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerChartAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerChart
        manager_type: orm
        group: "group.scores"
        label: "player_chart.label"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/PlayerChart/show.html.twig' ] ]
      - [ setEventDispatcher, [ '@event_dispatcher' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.playerchart_lib:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerChartLibAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerChartLib
        manager_type: orm
        group: "group.games"
        label: "label.playerChartLib"
        show_in_dashboard: false
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.badge:
    class: VideoGamesRecords\CoreBundle\Admin\BadgeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Badge
        manager_type: orm
        group: "group.badge"
        label: "badge.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.country:
    class: VideoGamesRecords\CoreBundle\Admin\CountryAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Country
        manager_type: orm
        group: "group.players"
        label: "country.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.rule:
    class: VideoGamesRecords\CoreBundle\Admin\RuleAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Rule
        manager_type: orm
        group: "group.games"
        label: "rule.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.discord:
    class: VideoGamesRecords\CoreBundle\Admin\DiscordAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Discord
        manager_type: orm
        group: "group.community"
        label: "discord.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.vgr.tag:
    class: VideoGamesRecords\CoreBundle\Admin\TagAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Tag
        manager_type: orm
        group: "group.config"
        label: "tag.label"
    calls:
      - [ setTranslationDomain, [ 'VgrCoreAdmin' ] ]
  sonata.admin.extension.workflow.game_status:
    class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
    arguments:
      - '@workflow.registry'
