services:
  sonata.admin.vgr.platform:
    class: VideoGamesRecords\CoreBundle\Admin\PlatformAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Platform
        manager_type: orm
        group: "group.games"
        label: "label.platform"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Platform/show.html.twig' ] ]
  sonata.admin.vgr.serie:
    class: VideoGamesRecords\CoreBundle\Admin\SerieAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Serie
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\SerieAdminController
        manager_type: orm
        group: "group.games"
        label: "label.serie"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Serie/show.html.twig' ] ]
  sonata.admin.vgr.game:
    class: VideoGamesRecords\CoreBundle\Admin\GameAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Game
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\GameAdminController
        manager_type: orm
        group: "group.games"
        label: "label.game"
        default: true
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Game/show.html.twig' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
  sonata.admin.vgr.group:
    class: VideoGamesRecords\CoreBundle\Admin\GroupAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Group
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\GroupAdminController
        manager_type: orm
        group: "group.games"
        label: "label.group"
  sonata.admin.vgr.chart:
    class: VideoGamesRecords\CoreBundle\Admin\ChartAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Chart
        manager_type: orm
        group: "group.games"
        label: "label.chart"
  sonata.admin.vgr.chart_type:
    class: VideoGamesRecords\CoreBundle\Admin\ChartTypeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\ChartType
        manager_type: orm
        group: "group.games"
        label: "label.chart.type"
  sonata.admin.vgr.chart_lib:
    class: VideoGamesRecords\CoreBundle\Admin\ChartLibAdmin
    tags:
      - name: sonata.admin
        model_class: 'VideoGamesRecords\CoreBundle\Entity\ChartLib'
        manager_type: orm
        group: "group.games"
        label: "label.chart.lib"
        show_in_dashboard: false
  sonata.admin.vgr.proof_request:
    class: VideoGamesRecords\CoreBundle\Admin\ProofRequestAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\ProofRequest
        manager_type: orm
        group: "group.proofs"
        label: "label.request"
    calls:
      - [ setTemplate, [ 'edit', '@@VideoGamesRecordsCore/Admin/Object/ProofRequest/edit.html.twig' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
  sonata.admin.vgr.proof:
    class: VideoGamesRecords\CoreBundle\Admin\ProofAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Proof
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\ProofAdminController
        manager_type: orm
        group: "group.proofs"
        label: "label.proof"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Proof/show.html.twig' ] ]
      - [ setTemplate, [ 'edit', '@@VideoGamesRecordsCore/Admin/Object/Proof/edit.html.twig' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
      - [ setSecurity, [ '@security.helper' ] ]
  sonata.admin.vgr.picture:
    class: VideoGamesRecords\CoreBundle\Admin\PictureAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Picture
        manager_type: orm
        group: "group.proofs"
        label: "label.picture"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Picture/show.html.twig' ] ]
  sonata.admin.vgr.video:
    class: VideoGamesRecords\CoreBundle\Admin\VideoAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Video
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\VideoAdminController
        manager_type: orm
        group: "group.proofs"
        label: "label.video"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Video/show.html.twig' ] ]
  sonata.admin.vgr.player:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Player
        controller: VideoGamesRecords\CoreBundle\Controller\Admin\PlayerAdminController
        manager_type: orm
        group: "group.players"
        label: "label.player"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/Player/show.html.twig' ] ]
  sonata.admin.vgr.playerbadge:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerBadgeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerBadge
        manager_type: orm
        group: "group.badge"
        label: "label.player"
  sonata.admin.vgr.team:
    class: VideoGamesRecords\CoreBundle\Admin\TeamAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Team
        manager_type: orm
        group: "group.players"
        label: "label.team"
  sonata.admin.vgr.team_request:
    class: VideoGamesRecords\CoreBundle\Admin\TeamRequestAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\TeamRequest
        manager_type: orm
        group: "group.players"
        label: "label.request"
  sonata.admin.vgr.playerchart:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerChartAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerChart
        manager_type: orm
        group: "group.scores"
        label: "label.playerChart"
    calls:
      - [ setTemplate, [ 'show', '@@VideoGamesRecordsCore/Admin/Object/PlayerChart/show.html.twig' ] ]
      - [ setEventDispatcher, [ '@event_dispatcher' ] ]
      - [ setRequestStack, [ '@request_stack' ] ]
  sonata.admin.vgr.playerchart_lib:
    class: VideoGamesRecords\CoreBundle\Admin\PlayerChartLibAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\PlayerChartLib
        manager_type: orm
        group: "group.games"
        label: "label.playerChartLib"
        show_in_dashboard: false
  sonata.admin.vgr.badge:
    class: VideoGamesRecords\CoreBundle\Admin\BadgeAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Badge
        manager_type: orm
        group: "group.badge"
        label: "label.badge"
  sonata.admin.vgr.country:
    class: VideoGamesRecords\CoreBundle\Admin\CountryAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Country
        manager_type: orm
        group: "group.players"
        label: "label.country"
  sonata.admin.vgr.game_day:
    class: VideoGamesRecords\CoreBundle\Admin\GameDayAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\GameDay
        manager_type: orm
        group: "group.others"
        label: "label.game.day"
  sonata.admin.vgr.rule:
    class: VideoGamesRecords\CoreBundle\Admin\RuleAdmin
    tags:
      - name: sonata.admin
        model_class: VideoGamesRecords\CoreBundle\Entity\Rule
        manager_type: orm
        group: "group.games"
        label: "label.rules"
  sonata.admin.extension.workflow.game_status:
    class: Yokai\SonataWorkflow\Admin\Extension\WorkflowExtension
    arguments:
      - '@workflow.registry'
