services:
  _defaults:
    autowire: true
    autoconfigure: true

  VideoGamesRecords\CoreBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  vgr.core.event.authentication_success_listener:
    class: VideoGamesRecords\CoreBundle\EventListener\AuthenticationSuccessListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

  admin.block.service.proof.games:
    class: VideoGamesRecords\CoreBundle\Block\Service\ProofGamesBlockService
    tags:
      - { name: "sonata.block" }

  admin.block.service.game.status:
    class: VideoGamesRecords\CoreBundle\Block\Service\GameStatusBlockService
    tags:
      - { name: "sonata.block" }


  VideoGamesRecords\CoreBundle\EventSubscriber\Api\PlayerChartSubscriber:
    tags:
      - { name: kernel.event_subscriber }



