VideoGamesRecords\CoreBundle\Entity\ChartType:
  attributes:
    id:
      groups:
        - 'chart.show'
        - 'playerChart.read'
        - 'playerChart.write'
    name:
      groups: []
    mask:
      groups:
        - 'chart.show'
        - 'playerChart.read'
        - 'playerChart.write'
    parseMask:
      groups:
        - 'chart.show'
        - 'playerChart.read'
        - 'playerChart.write'
